### ISSUE TITLE
Release SRIOV Network Operator v1.1.0

### ISSUE THREAD

**Issue by e0ne** [k8snetworkplumbingwg/sriov-network-operator#189]
We don't have a new release for a long time. We've got a lot of things merged [since initial community release](https://github.com/k8snetworkplumbingwg/sriov-network-operator/compare/v1.0.0...master). 

It's good to include following items in a new release:

- [x] New sriov-cni image: https://github.com/k8snetworkplumbingwg/sriov-cni/issues/198
- [x] New ib-sriov-cni image: https://github.com/k8snetworkplumbingwg/ib-sriov-cni/issues/61
- [x] Update sriov-network-device-plugin: https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/385
- [x] Update network-resources-injector: https://github.com/k8snetworkplumbingwg/network-resources-injector/issues/116
- [ ] Close #185
- [x] Add new chart to https://github.com/k8snetworkplumbingwg/helm-charts [#11](https://github.com/k8snetworkplumbingwg/helm-charts/issues/11)

**Comment by adrianchiris** [comment]
Hey Folks,
All dependent components have been released. shall we compile a list of PRs we want to target to be merged before release ?

**Comment by e0ne** [comment]
There aren't any specific requests from me

**Comment by zshi-redhat** [comment]
No particular request from me.

**Comment by adrianchiris** [comment]
Will do a release later today

**Comment by adrianchiris** [comment]
@e0ne can you work on the helm chart ? thats the last missing piece :)

im thinking we can have it in helm-charts repo as well as a tarball in the release assets WDYT ?

**Comment by e0ne** [comment]
Helm chart is published https://github.com/k8snetworkplumbingwg/helm-charts/pull/12
