### ISSUE TITLE
release 1.0.0 tracker

### ISSUE THREAD

**Issue by pliurh** [k8snetworkplumbingwg/sriov-network-operator#79]
release 1.0.0 work items:

- [x] #39 Support changing Eswitch mode of SR-IOV NICs for kubernetes deployment
- [x] #72 Set link state up for target ports of SriovNetworkNodePolicy for kubernetes cluster
- [x] #62 Support CLUSTER_TYPE env var
- [x] #75 Support Switchdev for kernel 5.8 and above
- [x] #71 Updating the hardware compatibility list
- [x] #82 GitHub container registry workflow

**Comment by pliurh** [comment]
@zshi-redhat @moshe010 @adrianchiris @martinkennelly @Mmduh-483

**Comment by adrianchiris** [comment]
PR #75  is merged

**Comment by adrianchiris** [comment]
PR #62 is merged

**Comment by adrianchiris** [comment]
Do we have outstanding PRs that need to be merged for the 1.0.0 Release?

**Comment by pliurh** [comment]
> Do we have outstanding PRs that need to be merged for the 1.0.0 Release?

I don't think there is any. If everyone agrees, we can release 1.0.0. @martinkennelly @zshi-redhat

**Comment by zshi-redhat** [comment]
> > Do we have outstanding PRs that need to be merged for the 1.0.0 Release?
> 
> I don't think there is any. If everyone agrees, we can release 1.0.0. @martinkennelly @zshi-redhat

+1

**Comment by martinkennelly** [comment]
> > Do we have outstanding PRs that need to be merged for the 1.0.0 Release?
> 
> I don't think there is any. If everyone agrees, we can release 1.0.0. @martinkennelly @zshi-redhat

+1

**Comment by pliurh** [comment]
https://github.com/k8snetworkplumbingwg/sriov-network-operator/releases/tag/v1.0.0
